// Exemplo COBOL para xHarbour
PROCEDURE Main()

    // DIVISÕES COBOL
    IDENTIFICATION DIVISION.
    DATA DIVISION.
    WORKING-STORAGE SECTION.
    
    // DECLARAÇÕES COBOL
    01 WS-NOME     PIC X(20) VALUE SPACES.
    01 WS-IDADE    PIC 9(3)  VALUE ZEROS.
    01 WS-SALARIO  PIC 9(6)V99 VALUE ZEROS.
    01 WS-ATIVO    PIC X VALUE 'N'.
    
    PROCEDURE DIVISION.
    
    // MOVE E DISPLAY
    MOVE "JOAO DA SILVA" TO WS-NOME
    MOVE 35 TO WS-IDADE
    MOVE 2500.50 TO WS-SALARIO
    MOVE 'S' TO WS-ATIVO
    
    DISPLAY "NOME: " WS-NOME
    DISPLAY "IDADE: " WS-IDADE
    DISPLAY "SALARIO: " WS-SALARIO
    DISPLAY "ATIVO: " WS-ATIVO
    
    // IF/THEN/ELSE
    IF WS-IDADE GREATER 18 THEN
        DISPLAY "MAIOR DE IDADE"
    ELSE
        DISPLAY "MENOR DE IDADE"
    END-IF
    
    // PERFORM LOOP
    PERFORM VARYING WS-IDADE FROM 1 BY 1 UNTIL WS-IDADE GREATER 5
        DISPLAY "CONTAGEM: " WS-IDADE
    END-PERFORM
    
    // CALL (função)
    CALL "CALCULA_BONUS" USING WS-SALARIO
    
    STOP RUN
    
RETURN

// SUBPROGRAMA
PROCEDURE CALCULA_BONUS(nSalario)
    LOCAL nBonus
    nBonus := nSalario * 0.10
    DISPLAY "BONUS: " nBonus
RETURN